### ISSUE TITLE
确认下valueTypes字段类型中，字符串，数字，金额，日期类型字段是否都支持min、max功能

### ISSUE THREAD

**Issue by yinlianghui** [steedos/app-builder#118]
不支持就加上，就是支持在yml文件字段配置中加上的min、max属性。

**Comment by Flyingliao** [comment]
- [ ] 1、字符串(text) 支持： 表示字符串的min、max长度.
- [ ] 2、数字、金额支持：表示min、max值。
- [ ] 3、日期字段报错。YYYY-MM-DD  、 'YYYY-MM-DD' 、moment('2021-01-01') 都报错

**Comment by Flyingliao** [comment]
antd中日期字段没有min、max属性，项目中也没有该字段需要支持min、max功能的issue，暂停不处理该功能。
