### ISSUE TITLE
lookup中配置filtersFunction时，如果是弹出窗口显示选项，未支持返回odata串，只支持了返回数组格式

### ISSUE THREAD

**Issue by yinlianghui** [steedos/app-builder#122]
- 该问题是为了兼容之前写过的老的filtersFunction函数
- 在之前用proTable的时候应该没这个问题，需要先排查下ObjectGrid是否支持传入字符串格式的过滤条件

**Comment by Flyingliao** [comment]
63548b1d359e513a21e05ebc01d09b919f09216f
