### ISSUE TITLE
lookup 如果配置了optionsFunction，在只读时，未能显示值， 需要双击进入编辑模式后才显示

### ISSUE THREAD

**Issue by baozhoutao** [steedos/app-builder#136]
![image](https://user-images.githubusercontent.com/6194462/123655402-859cb880-d861-11eb-803d-4e41dd27d2c1.png)
![image](https://user-images.githubusercontent.com/6194462/123655433-8cc3c680-d861-11eb-9c60-37b563e800ea.png)

**Comment by Flyingliao** [comment]
![image](https://user-images.githubusercontent.com/41402189/124410460-13eece00-dd7d-11eb-94cf-1723e70d148b.png)
