### ISSUE TITLE
toggle、boolean 只读样式调整

### ISSUE THREAD

**Issue by hotlong** [steedos/app-builder#170]
## toggle 字段
- 如果字段可编辑，均显示为禁用状态，点击浮出编辑框。（未来可优化为始终显示、直接选择。）
- 如果字段只读，保留现状。
<img width="225" alt="企业微信截图_b5716b5f-488b-4e28-bccf-6a236377188b" src="https://user-images.githubusercontent.com/50353452/125386796-74aa8600-e3cf-11eb-924a-e776f375c735.png">

## boolean 字段
- 如果字段可编辑，未选中时显示虚线的方框
- 如果字段只读，未选中时显示为空
<img width="748" alt="企业微信截图_23f471fe-8b78-42b0-924a-a71d2607df54" src="https://user-images.githubusercontent.com/50353452/125387492-98ba9700-e3d0-11eb-895b-3a2fa162a14d.png">

**Comment by Flyingliao** [comment]
**点击浮出编辑框。（未来可优化为始终显示、直接选择。）** : 只剩这个没处理，以后有这个需求再改
