### ISSUE TITLE
单选lookup字段弹出列表窗口，如果输入了过滤条件在过滤结果中未选中任何记录点击确认时会把原有的字段值清除

### ISSUE THREAD

**Issue by yinlianghui** [steedos/app-builder#184]
- 目前已上到建华项目的线上版本也有这个问题
- 多选的字段不会有这个问题，只有单选字段才有
- 点击取消按钮没关系，只有点击确认按钮才会清除字段值
- 这个问题不严重，因为一般输入过滤条件会勾选要保存的值来保存而不会直接点击保存
- 如果在过滤结果中选中了值会保存选中的值不会有bug

**Comment by Flyingliao** [comment]
无法重现
