### ISSUE TITLE
公式字段是readonly在an-grid的搜索功能中不能输入值过滤

### ISSUE THREAD

**Issue by yinlianghui** [steedos/app-builder#191]
应该是所有的readonly字段都有这个问题，需要统一处理。
![image](https://user-images.githubusercontent.com/6219465/126616614-ff108009-eb1d-48a7-ae6f-4950d57b3912.png)

**Comment by baozhoutao** [comment]
底层字段很奇怪，设置了redonly = true, mode=edit 时，还是可以编辑。但是只有部分是不可以编辑的。
公式、汇总类型字段需要考虑字段值类型，使用不同类型的字段进行搜索。

**Comment by yinlianghui** [comment]
已处理，公式及汇总字段会按其date_type类型处理。
