### ISSUE TITLE
日期时间字段在ag-grid表头的过滤界面中可能显示不全，应该设置下最小宽度

### ISSUE THREAD

**Issue by yinlianghui** [steedos/app-builder#195]
- 实在不行就始终显示两行吧。
- 应该是字段在靠右边才有这个问题，越靠右边宽度越小
![image](https://user-images.githubusercontent.com/6219465/126858763-5a0aa58d-25fd-4000-b2f3-832e1e257b56.png)

**Comment by Flyingliao** [comment]
之前尝试过 一行两列 并且设置每列最小宽度，但是当其自动换为两行时，每行的宽度都不是100%；
所以启用 始终显示两行 的代码吧。
