### ISSUE TITLE
手机端样式调整：选人样式等

### ISSUE THREAD

**Issue by Flyingliao** [steedos/app-builder#232]
![image](https://user-images.githubusercontent.com/41402189/129444775-01527fd7-4854-4307-9f44-e8d65e30f9ba.png)

**Comment by lizhenghotoa** [comment]
2.1版本选人控件移动端样式
![image](https://user-images.githubusercontent.com/26241897/131430228-a76ce294-a34d-44fa-bc99-edebb9e48213.png)
