### ISSUE TITLE
服务管理：工具申请、资源排期新增数据问题。

### ISSUE THREAD

**Issue by daiweishu** [steedos/app-builder#30]
填写好字段后点击 确定，页面没有反应，但是数据是新增成功的。
资源排期对象同样问题。
![image](https://user-images.githubusercontent.com/75776429/116048642-f2e86d80-a6a7-11eb-8d50-90966d067a52.png)

**Comment by yinlianghui** [comment]
非前端程序问题，是公式配置错了
