### ISSUE TITLE
登录界面输入用户名密码之后还是跳转回登录界面了

### ISSUE THREAD

**Issue by yinlianghui** [steedos/app-builder#39]
需要手动把url上的login后缀去掉才能正常进入主页

**Comment by lizhenghotoa** [comment]
http://192.168.0.190:5000/login登陆成功后，页面跳转地址如下，并不能成功跳转系统使用界面
http://192.168.0.190:5000/login?X-Space-Id=L9dbHwbvaD9f6B2aj&X-Auth-Token=32b13b0ad6887424503d8bf10bcb2df5ac2cf6a51f3df8ea2d166d06e88e40512edf019d49e4fa90b800e9&X-User-Id=61288c02bdc9890a9fe16fa7
