### ISSUE TITLE
react-demo-app中发现的选人组件权限问题确认下在我们正式的选人组织是否也存在

### ISSUE THREAD

**Issue by yinlianghui** [steedos/app-builder#75]
现象是属性某个分部的普通用户点开选人，右侧人员列表显示了所有人员信息，并没有只显示其所属分部的人员信息。
先测试下，有bug就按react-demo-app一样处理。

原因是执行setSpaceUsersFilters的useEffect函数中未监听User.isLoading属性。
选组组件也一样测试下。

**Comment by Flyingliao** [comment]
react-webapp中测试正常
