### ISSUE TITLE
在 grid 控件以外的地方点击鼠标，应该关闭弹出的编辑框

### ISSUE THREAD

**Issue by hotlong** [steedos/app-builder#79]
停止编辑： gridApi.stopEditing():  // If you call stopEditing() on the grid API.
可能的参数：stopEditingWhenCellsLoseFocus

**Comment by hotlong** [comment]
stopEditingWhenCellsLoseFocus， stopEditingWhenGridLoseFocus不行，我们的需求是要把当前的单元格中弹出的编辑框关掉，而不是彻底停止表格中的数据编辑。

**Comment by baozhoutao** [comment]
相关任务：https://github.com/steedos/steedos-project-pcmes/issues/39

**Comment by hotlong** [comment]
https://www.npmjs.com/package/react-click-outside 用这个封装 CellEditor 应该可以
