### ISSUE TITLE
对象配置了enable_tree未配置enable_enhanced_lookup时，表单上的lookup字段功能异常

### ISSUE THREAD

**Issue by yinlianghui** [steedos/app-builder#92]
这时会显示下拉列表的tree组件，用的proField的tree组件，我记得之前是好的，现在坏了。
![image](https://user-images.githubusercontent.com/6219465/122671082-a2007b80-d1f7-11eb-8bcb-003b12c562aa.png)

**Comment by Flyingliao** [comment]
tree 的功能要重新测试 和  修复。

**Comment by Flyingliao** [comment]
对organizations对象进行测试，结果正常。

**Comment by Flyingliao** [comment]
未支持 ： parent_field
